#!/usr/bin/env python3
"""
Generate simple markdown report for GitHub viewing
"""

import json
import os
from datetime import datetime

def load_metrics():
    """Load metrics from JSONL file"""
    metrics = []
    if os.path.exists('performance-metrics.jsonl'):
        with open('performance-metrics.jsonl', 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        metrics.append(json.loads(line))
                    except json.JSONDecodeError:
                        continue
    return metrics

def generate_markdown_report(metrics):
    """Generate markdown report with security findings"""
    
    if not metrics:
        return """# 🔒 Security Analysis Report

⚠️ No metrics collected. Check workflow logs for issues.

## Next Steps
1. Verify security analysis tools are configured with proper tokens
2. Check individual job logs for execution errors
3. Ensure metrics collection scripts have proper permissions
"""

    total_tools = len({m['tool'] for m in metrics})
    total_duration = sum(m['duration_seconds'] for m in metrics)
    
    # Calculate total vulnerabilities
    total_vulnerabilities = 0
    for metric in metrics:
        findings = metric.get('security_findings', {})
        if isinstance(findings.get('total_vulnerabilities'), int):
            total_vulnerabilities += findings['total_vulnerabilities']
    
    report = f"""# 🔒 Security Analysis Report

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}  
**Tools Analyzed**: {total_tools}  
**Total Analysis Time**: {total_duration}s  
**Total Vulnerabilities Found**: {total_vulnerabilities}

## � Security Findings

| Tool | Total Issues | High | Medium | Low | Top Issues |
|------|-------------|------|--------|-----|------------|
"""

    # Add security findings rows
    for metric in metrics:
        findings = metric.get('security_findings', {})
        total_vulns = findings.get('total_vulnerabilities', 'N/A')
        high_vulns = findings.get('high_severity', 'N/A')
        med_vulns = findings.get('medium_severity', 'N/A')
        low_vulns = findings.get('low_severity', 'N/A')
        top_issues = findings.get('top_issues', 'None detected')
        
        # Handle special values
        if total_vulns == 'github_stored':
            total_vulns = '[View in Security Tab](../../security/code-scanning)'
            high_vulns = med_vulns = low_vulns = '-'
            top_issues = 'Results in GitHub Security tab'
        elif total_vulns == 'sonarcloud_stored':
            total_vulns = '[View in SonarCloud](https://sonarcloud.io)'
            high_vulns = med_vulns = low_vulns = '-'
            top_issues = 'Results in SonarCloud'
        
        # Truncate top issues for markdown table
        if len(top_issues) > 50:
            top_issues = top_issues[:50] + '...'
        
        # Replace semicolons with commas for better markdown display
        top_issues = top_issues.replace(';', ', ')
        
        report += f"| {metric['tool']} | {total_vulns} | {high_vulns} | {med_vulns} | {low_vulns} | {top_issues} |\n"

    report += f"""
## ⚡ Performance Overview

| Tool | Duration | Lines of Code | Performance Ratio | Status |
|------|----------|---------------|-------------------|--------|
"""
    
    for metric in metrics:
        tool = metric.get('tool', 'Unknown')
        duration = metric.get('duration_seconds', 0)
        
        # Handle different LOC structures
        if isinstance(metric.get('lines_of_code'), dict):
            loc = metric['lines_of_code'].get('total', 0)
        else:
            loc = metric.get('lines_of_code', 0)
        
        ratio = float(metric.get('performance_ratio', 0))
        
        if ratio < 0.001:
            status = '🚀 Fast'
        elif ratio < 0.01:
            status = '⚡ Normal'
        else:
            status = '🐌 Slow'
        
        report += f"| {tool} | {duration}s | {loc:,} | {ratio:.6f} | {status} |\n"
    
    report += """
## 📍 Access Full Results

- **Complete HTML Report**: Download `performance-metrics-report` artifact from this workflow run
- **Security Findings**: Navigate to repository **Security** tab → **Code scanning**
- **Raw Metrics**: Available in workflow artifacts as `performance-metrics.jsonl`
- **Trend Analysis**: Performance regression alerts appear in workflow logs

## 📋 Performance Benchmarks

- **🚀 Fast**: < 0.001 sec/LOC
- **⚡ Normal**: 0.001-0.01 sec/LOC  
- **🐌 Slow**: > 0.01 sec/LOC

---
*This report is automatically generated by the security analysis workflow*
"""
    
    return report

def main():
    """Main function"""
    metrics = load_metrics()
    markdown_report = generate_markdown_report(metrics)
    
    # Write to README-like file that can be viewed directly on GitHub
    with open('SECURITY_PERFORMANCE_REPORT.md', 'w', encoding='utf-8') as f:
        f.write(markdown_report)
    
    print("✅ Markdown report generated: SECURITY_PERFORMANCE_REPORT.md")
    print("📄 This file can be viewed directly on GitHub without downloading")

if __name__ == "__main__":
    main()
